### ISSUE TITLE
New release that uses clang-sys ^0.26

### ISSUE THREAD

**Issue by stillinbeta** [KyleMayes/clang-rs#15]
Recent `bindgen`s [depend on clang-sys ^0.26](https://crates.io/crates/bindgen). The most recent release of clang-rs depends on `0.23`. That unfortunately means I can't use both in the same project (see https://github.com/bluejekyll/pg-extend-rs/pull/20 for my motivating example)

**Comment by KyleMayes** [comment]
Released as `v0.21.0`.

**Comment by stillinbeta** [comment]
Thank you!
