### ISSUE TITLE
Entity as enum

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-rs#2]
Did you consider making Entity an enum? It would nable the use of pattern matching.

**Comment by KyleMayes** [comment]
Interesting, I had not thought about that.

Do you mean something like:

```
match entity {

}
```

**Comment by KyleMayes** [comment]
Interesting, I hadn't thought about that.

Another idea would be to leave `Entity` as a struct but add fields that are specific to only a few `EntityKind`s to the `EntityKind` variant.

E.g., `Entity::get_file` would be removed (because it is only used for inclusion directives) and the `EntityKind::InclusionDirective` variant would become `EntityKind::InclusionDirective(File<'tu>)`.

I'll have to think about it.

**Comment by KyleMayes** [comment]
I've thought about it, and I'm not sure it's worth the implementation difficulty. There would still be many fields common to most entity kinds.

```rust
if let Entity::InclusionDirective(file) = entity {
    let name = entity.get_name().unwrap();
}
```

doesn't seem much better than

```rust
if entity.get_kind() == EntityKind::InclusionDirective {
    let name = entity.get_name().unwrap();
    let file = entity.get_file().unwrap();
}
```

to me.

There's less `unwrap` with the pattern matching, but it wouldn't eliminate it completely. Some entities would still have an optional name and some would still have an optional source range.

**Comment by KyleMayes** [comment]
However, something like

```rust
if let EntityKind::InclusionDirective(file) = entity.get_kind() {
    let name = entity.get_name().unwrap();
}
```

might work. I'll start looking into it.

**Comment by KyleMayes** [comment]
Well I tried, but it doesn't seem practical to map `libclang`'s API into anything other than what it is now.

**Comment by Yamakaky** [comment]
The you crate is not really rust idiomatic ;)

**Comment by KyleMayes** [comment]
Yeah, it kinda sucks. It's still 100x easier to use than the raw bindings.

The `libclang` API is just really awkward, even as C APIs go.

**Comment by KyleMayes** [comment]
d7507ed4a8c04d16013adc27a108fc49e3a9ccb1

**Comment by Yamakaky** [comment]
This crate will not be used a lot (only crates which manipulates c code), so it's not a big issue.
