### ISSUE TITLE
Entity.get_platform_availability() crashing on double free

### ISSUE THREAD

**Issue by vincentisambart** [KyleMayes/clang-rs#25]
When trying to call `Entity.get_platform_availability()`, my program crashes with the following message:
```
malloc: *** error for object 0x100704370: pointer being freed was not allocated
```

Looking at the stack track in the debugger it happens inside `clang_disposeCXPlatformAvailability`.
Having a look at the clang source code, [`clang_disposeCXPlatformAvailability`](https://github.com/llvm/llvm-project/blob/5625e6ab3788a788662f48dc7f5119defb43f08d/clang/tools/libclang/CIndex.cpp#L8018-L8021) is pretty simple:
```c++
void clang_disposeCXPlatformAvailability(CXPlatformAvailability *availability) {
  clang_disposeString(availability->Platform);
  clang_disposeString(availability->Message);
}
```

It seems at least one of the strings has been freed somewhere else.
And looking  a bit more at the clang-rs source they are indeed already freed when converted to Rust string:
```rust
impl PlatformAvailability {
    fn from_raw(mut raw: CXPlatformAvailability) -> PlatformAvailability {
        let availability = PlatformAvailability {
            platform: utility::to_string(raw.Platform),
            unavailable: raw.Unavailable != 0,
            introduced: raw.Introduced.map(Version::from_raw),
            deprecated: raw.Deprecated.map(Version::from_raw),
            obsoleted: raw.Obsoleted.map(Version::from_raw),
            message: utility::to_string_option(raw.Message),
        };
        unsafe { clang_disposeCXPlatformAvailability(&mut raw); }
        availability
    }
}
```

with `utility::to_string` being:
```rust
pub fn to_string(clang: CXString) -> String {
    unsafe {
        let c = CStr::from_ptr(clang_getCString(clang));
        let rust = c.to_str().expect("invalid Rust string").into();
        clang_disposeString(clang);
        rust
    }
}
```

I'm not sure it is the best fix but I guess removing the call to `clang_disposeCXPlatformAvailability` would fix the crash?

**Comment by KyleMayes** [comment]
Fixed in `v1.0.1`.
