### ISSUE TITLE
New release that uses clang_sys 1.0

### ISSUE THREAD

**Issue by lovesegfault** [KyleMayes/clang-rs#33]
This is blocking adoption of `clang_sys` 1.0 across the broader ecosystem. In particular in `opencv-rs`, https://github.com/twistedfall/opencv-rust/issues/159

**Comment by KyleMayes** [comment]
Released `v1.0.0` with Clang 10 support and `clang-sys` `v1.0.0`.

**Comment by lovesegfault** [comment]
Cheers!
