### ISSUE TITLE
Need help: How to compile C source files

### ISSUE THREAD

**Issue by mrLSD** [KyleMayes/clang-rs#37]
I know that it's possible to compile C source data to obj-file, or executable files with `libclang`.

Could you provide some practical example in rust for `libclang` for very basic operations that possible to do with CLI:
* `clang myfile.c -c -o myfile.o`
* `clang myfile2.c myfile.o -o myapp`

It will be really helpful to know how to do that with Rust using `libclang`.
Or to do the same things for `ll` files (LLVM IR source files).

**Comment by KyleMayes** [comment]
In the words of the [`libclang` documentation](https://clang.llvm.org/doxygen/group__CINDEX.html#details):

```
The C Interface to Clang provides a relatively small API that exposes facilities for parsing source code
into an abstract syntax tree (AST), loading already-parsed ASTs, traversing the AST, associating physical
source locations with elements within the AST, and other facilities that support Clang-based development
tools.

This C interface to Clang will never provide all of the information representation stored in Clang's C++ AST,
nor should it: the intent is to maintain an API that is relatively stable from one release to the next, providing
only the basic functionality needed to support development tools.
```

`libclang` only offers a small subset of the full C++ Clang API, tasks like compiling code are not supported.

If you want to do this from Rust, I'm not sure what the easiest way would be, but I think you could write a C or C++ library which wraps the full C++ Clang API and does what you want to do and then generate Rust bindings to that library using [`rust-bindgen`](https://github.com/rust-lang/rust-bindgen).
