### ISSUE TITLE
obtain the const type

### ISSUE THREAD

**Issue by luke-titley** [KyleMayes/clang-rs#38]
Hey,
Is there a way to obtain the inside type of a const type.
I know in the api I can invoke.

```
type_.is_const_qualified()
```

but how can I obtain the type that is const qualified?

For example if I have a type that is:
```
const int
```

is there a way to get hold of:
```
int
```

**Comment by KyleMayes** [comment]
A `CXType` in `libclang` is a wrapper around a `QualType` (qualified type) in `clang` so it looks like what you want to do is call `QualType::getUnqualifiedType()` to get the "unqualified" type.

Unfortunately this function is not directly exposed in `libclang`, so I don't believe what you are asking for is possible in the general case. There is a 2 year old thread on the mailing list where someone else asks for this and adding this to `libclang` is discussed but no action was taken: http://clang-developers.42468.n3.nabble.com/libclang-Getting-unqualified-version-of-Type-td4059588.html
