### ISSUE TITLE
Update to clang-sys 0.8

### ISSUE THREAD

**Issue by jupp0r** [KyleMayes/clang-rs#4]
Hey,

any particular reason you haven't bumped the clang-sys dependency? 0.8 enables me to build under OS X.

**Comment by KyleMayes** [comment]
I have been delayed. I added AppVeyor support, which notified me that some of the tests were failing on Windows. I'm fixing that right now, and the next version of this will be released soon.

**Comment by KyleMayes** [comment]
`v0.10.0` has been released!

**Comment by jupp0r** [comment]
Cool, thanks!
