### ISSUE TITLE
Why was Send and Sync disabled for Clang struct in v2.0.0?

### ISSUE THREAD

**Issue by twistedfall** [KyleMayes/clang-rs#44]
Hi Kyle,

Can you please explain reasoning behind disabling autoimpls for Send and Sync in the new release of `clang`? Is it just a precaution or is there some issue with that?

Thanks!

**Comment by bonzini** [comment]
Disabling Send and Sync for Index is correct, because libclang is not thread-sae. However separate instances of CXIndex _can_ be used in different threads, so it's just the one-Clang-instance-only that is too restrictive.
