### ISSUE TITLE
No way to obtain the Opcode for a BinaryOperator Entity

### ISSUE THREAD

**Issue by eternaleye** [KyleMayes/clang-rs#5]
The C++ API allows doing this via the [`getOpcode()` method](http://clang.llvm.org/doxygen/classclang_1_1BinaryOperator.html#a497174c5cc2816aa3a3f29e12dd93165) of the `BinaryOperator` subclass of `Expr`.

The lack of this feature is noted as [one of the reasons Corrode was written in Haskell using `Language.C`, rather than Rust](https://github.com/jameysharp/corrode/issues/50#issuecomment-236098060)

**Comment by KyleMayes** [comment]
This crate is currently just a wrapper around the `libclang` C API, and the `libclang` C API lacks this ability. If you want the full power of `clang`, you pretty much have to go through their C++ API.

**Comment by eternaleye** [comment]
I'll shunt this upstream then - thanks!

By the way, neat X-29 in your avatar!

**Comment by eternaleye** [comment]
Upstream bug: https://llvm.org/bugs/show_bug.cgi?id=28768
