### ISSUE TITLE
How do I call clang::HeaderSearch?

### ISSUE THREAD

**Issue by shirakaba** [KyleMayes/clang-rs#52]
Essentially I'm trying to replicate what [this repo](https://github.com/NativeScript/ios/blob/6868a7a4c4db7d9447cd1cc457a112b88e6b2458/metadata-generator/src/main.cpp#L49) does (which is follow all the headers recursively and process all their declarations) but it starts with calling an API upon `clang::HeaderSearch`:

https://github.com/NativeScript/ios/blob/6868a7a4c4db7d9447cd1cc457a112b88e6b2458/metadata-generator/src/main.cpp#L49

Wondering how to do the same thing in `clang-rs`.

**Comment by KyleMayes** [comment]
This crate only provides what is available in Clang's C API (`libclang`): https://clang.llvm.org/doxygen/group__CINDEX.html.

It doesn't look like that header search API is included so you won't be able to do that with `clang-rs`.

A lot of the more advanced capabilities of Clang are only available through the full C++ API.
