### ISSUE TITLE
Add a switch for cpp?

### ISSUE THREAD

**Issue by sbant** [KyleMayes/clang-rs#8]
clang.exe has a switch to parse .h as cpp header file with "-x c++", or use clang++.exe

I want to parse a c++ header file with .h extension, now I can only rename it to .hpp to get parse correct.

Does libclang support this? Can this add to clang-rs?

**Comment by KyleMayes** [comment]
You can set Clang arguments when parsing translation units using [this method](http://kylemayes.github.io/clang-rs/5_0/clang/struct.Parser.html#method.arguments) on the `Parser` struct.

Have you tried this yet?

**Comment by sbant** [comment]
This solved the problem.

I use:
.arguments(&["-x", "c++"])

Thanks
