### ISSUE TITLE
Help wanted: get macro value

### ISSUE THREAD

**Issue by sbant** [KyleMayes/clang-rs#9]
I have spent several hours, but can't find solution. Please help..

I have some macro in header file like:
`#define SomeThing '1'`

in Rust I have these code:
```
let clang = Clang::new().unwrap();
let index = Index::new(&clang, false, false);

let tu = index.parser("file_path")
            .arguments(&["-x", "c++"])
            .detailed_preprocessing_record(true) // for macro
            .parse()
            .unwrap();

let children = tu.get_entity().get_children().into_iter();

for cursor in children {
	match cursor.get_kind() {
		EntityKind::MacroDefinition => {
			 // I can get macro name here, but can't get macro value.
		}
	}
}
```

in 
https://stackoverflow.com/questions/10113586/how-can-i-parse-macros-in-c-code-using-clang-as-the-parser-and-python-as-the

the solution for python:
`tu = index.parse(sys.argv[1], options=clang.cindex.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD)`

```
def visit(node):
    if node.kind in (clang.cindex.CursorKind.MACRO_INSTANTIATION, clang.cindex.CursorKind.MACRO_DEFINITION):
        print 'Found %s Type %s DATA %s Extent %s [line=%s, col=%s]' % (node.displayname, node.kind, node.data, node.extent, node.location.line, node.location.column)
    for c in node.get_children():
        visit(c)
```

but I can't find some method like "node.data" in clang-rs.

**Comment by KyleMayes** [comment]
You can get the value of a preprocessor definition by [tokenizing](http://kylemayes.github.io/clang-rs/5_0/clang/source/struct.SourceRange.html#method.tokenize) the source range the preprocessor definition occupies.

For example, if your preprocessor definition is `entity`, use `entity.get_range().unwrap().tokenize()` to get the tokens which make up the preprocessor definition. At this point it is now up to you to handle the tokens in whichever way you see fit as Clang does not help you here. The [cexpr](https://github.com/jethrogb/rust-cexpr) crate might be useful to you for this part.

You can see an example of extracting integers and reals from preprocessor definitions in the `sonar.rs` file [here](https://github.com/KyleMayes/clang-rs/blob/ea2e1514bc00e1b584acb49045f838a8e62f366e/src/sonar.rs#L41-L66).

**Comment by sbant** [comment]
Thanks, this solve the problem, although only get all marcros together, not keep the order (type and macro) in orginal header file.
